---
AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Enabled: true
  Exclude:
    - spec/**/*

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

