---
AllCops:
  TargetRubyVersion: 2.4

Metric/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metric/LineLength:
  Enabled: true
  Exclude:
    - spec/**/*

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

