---
development:
  API_URL: 'http://localhost:9292'
  DB_FILENAME: infrastructure/database/dev.db

test:
  API_URL: 'http://localhost:9292'
  DB_FILENAME: infrastructure/database/test.db

production:
  API_URL: 'https://taigo-apis.herokuapp.com'
